id: im.turms.plugin.livekit.LiveKitConferenceServicePlugin
class: im.turms.plugin.livekit.LiveKitConferenceServicePlugin
compatible-servers:
  - type: turms-service
version: 0.10.0
provider: im.turms
license: MIT
description: ''