id: im.turms.plugin.push.PushNotificationServicePlugin
class: im.turms.plugin.push.PushNotificationServicePlugin
compatible-servers:
  - type: turms-service
version: 0.10.0
provider: im.turms
license: MIT
description: ''